[package]
name = "stressed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
colored = "2.0.4"
indicatif = "0.17.5"
similar = "2.2.1"
