[package]
name = "stressed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.3.12"
colored = "2.0.4"
similar = "2.2.1"
