name: Rust

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Test format
        run: cargo fmt --check
          #      - name: Check CLI docs
          #        run: |
          #          cargo run --bin docgen ref_cli.md
          #          cmp --silent ref_cli.md docs/CLI.md
          #          rm ref_cli.md
      - name: Linux binary
        env:
          TARGET: x86_64-unknown-linux-musl
        run: |
          rustup target add $TARGET
          cargo build --release --target $TARGET --locked
          mv target/$TARGET/release/stressed stressed_$TARGET
          #      - name: Mac OS x86 binary
          #        env:
          #          TARGET: x86_64-apple-darwin
          #        run: |
          #          rustup target add $TARGET
          #          cargo build --release --target $TARGET --locked
          #          mv target/$TARGET/release/stressed stressed_$TARGET
          #      - name: Mac OS aarch64 binary
          #        env:
          #          TARGET: aarch64-apple-darwin
          #        run: |
          #          rustup target add $TARGET
          #          cargo build --release --target $TARGET --locked
          #          mv target/$TARGET/release/stressed stressed_$TARGET
      - name: Upload Linux release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            stressed_x86_64-unknown-linux-musl
            #            stressed_x86_64-apple-darwin
            #            stressed_aarch64-apple-darwin
